###############################
## DEPLOYMENT_VARIABLES.YAML ##
###############################
deployment:
  # 11 CHARACTERS OR LESS - Name the deployment something specific but readable - This is used for the DNS entry to the platform
  name: 'pov202108'
  environment: 'proving1'
  viya4:
    # Get this information from your POC Viya Order - https://apiportal.sas.com/get-started
    cadencename: 'stable'
    cadenceversion: '2021.1.2'
    ordernumber: '09XBMZ'
    orderapikey: 'DdaYBuk766TyYLZxgebyQNLOyRjdAQxG'
    orderapisecret: 'gra61ZprZbZGy4ml'
     # For INTERNAL ORDERS ONLY - https://cr.sas.com/tokens
    # cruser: 'q-4Afjov83E3IO'
    # crpassword: 'WfyaOTm647sF6Df7T-BtTlGPA6Rftrid.Zm8OD5VQ3trvTZT5mSVRHg1dzjLB7QDDM268Y6E3o3JgbomxtrA'
    # azurecr:
      # adminuser:
      # adminpassword:
  deployervm: # Deployment management VM to run all the CLI sofware and IAC deployment tasks from and administer most components during their lifetime
    azureresourcegroup: 'orchestration'
    azurestorageaccount: 'ssaimadeployresources'
    baseos: 
      name: 'ubuntu'
      version: '20.04'
    client: 
      terraform: 
        version: '1.0.0'
      azurecli: 
        version: '2.24.2'
      ansible: 
        version: '3.2.0'
        ansiblegalaxy:
          community:
            kubernetes:
              version: '1.2.1'
      kubectl:
        version: '1.19.11'
      kustomize: 
        version: "3.7.0"
      yq: 
        version: '3.4.0'
        binary: 'yq_linux_386'
      viya4ordercli:
        version: '1.0.0'
  deploymentresources:
    azureresourcegroup: 'orchestration'
    azurestorageaccount: 'ssaimadeployresources'
    filesharename: 'viya-deployment-resources'
  iac:
    azure:
      location: 'australiaeast'
      subscription: 'sas-ssaima'
      network:
        #192.31.37.2/32		vpn.sas.com/secure
        #13.70.89.145/32	sas-ssaima-envmgmt.australiaeast.cloudapp.azure.com
        defaultpublicaccesscidrs: "[\"192.31.37.2/32\"]"
    viya4iacazure: 
      iacazuretag: '3.1.0'
      storage: ## NB// This is the 'standard' configuration that creates and NFS server with RAID config the Premium NetApp service is not implemented in this automated deplyoment
        nfs:
          publicip: 'true'
          adminuser: 'nfsadmin'
          vm:
            machinetype: 'Standard_D4s_v4'
            zone: '1'
          raid:
            disktype: 'Standard_LRS'
            disksize: '64'
            diskzones: "[\"1\"]"
      nodepools:
        cas:
          machinetype: 'Standard_E8ds_v4'
          osdisksize: '200'
          minnodes: '1'
          maxnodes: '1'
          maxpods: '110'
        compute:
          machinetype: 'Standard_E2ds_v4'
          osdisksize: '50'
          minnodes: '1'
          maxnodes: '1'
          maxpods: '110'
        connect:
          machinetype: 'Standard_E2ds_v4'
          osdisksize: '50'
          minnodes: '1'
          maxnodes: '1'
          maxpods: '110'
        stateless:
          machinetype: 'Standard_E8ds_v4'
          osdisksize: '200'
          minnodes: '1'
          maxnodes: '2'
          maxpods: '110'
        stateful:
          machinetype: 'Standard_E4ds_v4'
          osdisksize: '200'
          minnodes: '1'
          maxnodes: '3'
          maxpods: '110'
      azurepostgres:
        version: '11'
        skuname: 'GP_Gen5_4'
        storagemb: '102400'
        daysofbackup: '7'
        adminlogin: 'pgadmin'
        adminpassword: 'KeysToTheData2021'
    viya4deployment:
      versiontag: '3.3.0'
      ingress:
        sourceranges: "[\"192.31.37.2/32\"]"
      metricsserver:
        version: '0.3.6'
      openldap:
        adminpassword: 'pov202105ldap'
        userlistingfilepath: ''




