###############################
## DEPLOYMENT_VARIABLES.YAML ##
###############################
deployment:
  # 11 CHARACTERS OR LESS - Name the deployment something specific but readable - This is used for the DNS entry to the platform
  name: 'pov202108'
  environment: 'proving1'
  azure:
    location: 'australiaeast'
    subscription: 'sas-ssaima'
    network:
      #192.31.37.2/32		vpn.sas.com/secure
      defaultpublicaccesscidrs: "[\"192.31.37.2/32\"]"
    resources:
      orchestrationresourcegroup: 'orchestration'
      storageaccount: 'ssaimadeployresources'
      filesharename: 'viya-deployment-resources'
  viya4:
    # Get this information from your POC Viya Order - https://apiportal.sas.com/get-started
    cadencename: 'stable'
    cadenceversion: '2021.1.2'
    ordernumber: '09XBMZ'
    orderapikey: 'DdaYBuk766TyYLZxgebyQNLOyRjdAQxG'
    orderapisecret: 'gra61ZprZbZGy4ml'
     # For INTERNAL ORDERS ONLY - https://cr.sas.com/tokens
    # cruser: 'q-4Afjov83E3IO'
    # crpassword: 'WfyaOTm647sF6Df7T-BtTlGPA6Rftrid.Zm8OD5VQ3trvTZT5mSVRHg1dzjLB7QDDM268Y6E3o3JgbomxtrA'
    # azurecr:
      # adminuser:
      # adminpassword: