###############################
## VIYA_DEPLOYMENT-VARIABLES.YAML ##
###############################
deployment:
  environment:
    ingress:
      sourceranges: "[\"0.0.0.0/0\"]"
    openldap:
      ldappassword: '${deployment_environment}_ldap'
      # viyaadminspassword is set for both the viya_admin user and sasboot
      viyaadminspassword: '${deployment_environment}_viya'
    secondpostgres:
      adminlogin: 'pgadmin'
      adminpassword: 'KeysToTheData2021'
